{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if hasKey $job "serviceAccount" }}
  {{- if hasKey $job.serviceAccount "name" }}
  name: {{ $job.serviceAccount.name }}
  {{- else }}
  name: {{ $job.name }}
  {{- end }}
  {{- end }}
  labels:
    app: {{ $release_name }}
    cron: {{ $job.name }}
  {{- if hasKey $job "serviceAccount" }}
  {{- if hasKey $job.serviceAccount "annotations" }}
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
